# Generated by Django 6.0.3 on 2026-03-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('gender', models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl'), ('Unisex', 'Unisex')], max_length=10)),
                ('age_group', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('discount', models.IntegerField(default=0)),
                ('is_premium', models.BooleanField(default=False)),
                ('collection', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
