# Generated by Django 6.0.3 on 2026-03-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_shop', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rental_period',
            field=models.CharField(blank=True, help_text='e.g. One day, Monthly, 10 days', max_length=50, null=True),
        ),
    ]
